# Generated by Django 4.2.7 on 2024-04-12 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastral_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_symbols', message='Это поле может содержать только кадастровый номер в формате "22:22:123555:215"', regex="^[0-9\\:,'\\s]+$()-")], verbose_name='Кадастровый номер')),
                ('latitude', models.CharField(max_length=10, verbose_name='Широта')),
                ('longitude', models.CharField(max_length=10, verbose_name='Долгота')),
                ('result', models.BooleanField(verbose_name='Результат запроса')),
                ('create_at', models.DateTimeField(auto_now=True, verbose_name='Создано')),
            ],
        ),
    ]
